[package]
name = "pop_circuit_ffa"
version = "0.1.0"
edition = "2021"

[dependencies]
midnight-proofs = { git = "https://github.com/midnightntwrk/midnight-zk", branch = "iquerejeta/ecdsa_pop" }
midnight-curves = { git = "https://github.com/midnightntwrk/midnight-zk", branch = "iquerejeta/ecdsa_pop" }
midnight-circuits = { git = "https://github.com/midnightntwrk/midnight-zk", branch = "iquerejeta/ecdsa_pop" }
midnight-zk-stdlib = { git = "https://github.com/midnightntwrk/midnight-zk", branch = "iquerejeta/ecdsa_pop" }
blake2b_simd = "1"
group = "0.13"
ff = "0.13"
rand = "0.8"

[dev-dependencies]
criterion = { version = "0.8", features = ["html_reports"] }

[features]
default = ["single-h-commitment"]
single-h-commitment = [
  "midnight-zk-stdlib/single-h-commitment",
  "midnight-proofs/single-h-commitment",
  "midnight-circuits/single-h-commitment",
]

[[example]]
name = "pop_circuit_ffa"
path = "examples/pop_circuit_ffa.rs"

[[bench]]
name = "ffa_circuit_daa"
harness = false

[[bench]]
name = "ffa_circuit_w"
harness = false
