[package]
name = "rok"
version = "0.1.0"
edition = "2021"
description = "An implementation of Reductions of Knowledge"
license = "MIT"
repository = "https://github.com/hpicrypto/ecdsa_pops"

[lib]
doctest = false

[dependencies]
merlin = { workspace = true }
bincode = { workspace = true }
thiserror = { workspace = true }
ark-std = { workspace = true }
serde = { workspace = true }
